# We need a decent ubuntu dist
sudo: required
dist: trusty

# Modern cpp settings from
#  http://genbattle.bitbucket.org/blog/2016/01/17/c++-travis-ci/
language: cpp
matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - g++-5
            - cmake
            - cmake-data
            
            # Additional Packages
            
            - git
            - pkg-config
            - git gfortran
            - libjpeg8-dev
            - libjasper-dev
            - libpng12-dev
            - libtiff5-dev
            - libtiff-dev
            - libavcodec-dev
            - libavformat-dev
            - libswscale-dev
            - libdc1394-22-dev
            - libxine2-dev
            - libv4l-dev
            - libgstreamer0.10-dev
            - libgstreamer-plugins-base0.10-dev
            - libgtk2.0-dev
            - libtbb-dev
            - qt5-default
            - libatlas-base-dev
            - libfaac-dev
            - libmp3lame-dev
            - libtheora-dev
            - libvorbis-dev
            - libxvidcore-dev
            - libopencore-amrnb-dev
            - libopencore-amrwb-dev
            - libavresample-dev
            - x264 v4l-utils
            - libprotobuf-dev
            - protobuf-compiler
            - libgoogle-glog-dev
            - libgflags-dev
            - libgphoto2-dev
            - libeigen3-dev
            - libhdf5-dev
            - doxygen
            - python3-dev
            - python3-pip
            - pip numpy
            - python3-testresources
      env: COMPILER=g++-5

before_script:
  - git clone https://github.com/opencv/opencv.git
  - cd opencv
  - git checkout master
  - cd ..

  - git clone https://github.com/opencv/opencv_contrib.git
  - cd opencv_contrib
  - git checkout master
  - cd ..

  - cd opencv
  - mkdir build
  - cd build
  - cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D WITH_TBB=ON -D WITH_V4L=ON -D WITH_QT=ON -D WITH_OPENGL=ON -D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib/modules ..
  - make -j$(nproc)
  - sudo make install
  - sudo sh -c 'echo "/usr/local/lib" >> /etc/ld.so.conf.d/opencv.conf'
  - sudo ldconfig

before_install:
  -pip install --user cpp-coveralls
install:
  - sudo apt-get install -y -qq lcov
script:
  - export CXX=$COMPILER;
  - mkdir build
  - cd build
  - cmake -DCOVERAGE=ON -DCMAKE_BUILD_TYPE=Debug ../
  - make
  - make code_coverage
  - test/cpp-test

after_success:
  - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"

notifications:
  email: false
